import { SessionProvider, useSession } from "next-auth/react"
import { auth } from "./auth";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = auth();
  console.log("I am called for session=", session);
  return (
    <html lang="en">
      <body>
        <SessionProvider>{children}</SessionProvider></body>
    </html>
  )
}
